import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Exercise 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <header className="h-12 bg-[#1b1b1b] flex  items-center px-4 py-9 border-b ">
            <h1 className="text-3xl font-semibold text-[#9a2678]">APIConnection-Exercise1</h1>
        </header>
          {children}
        </body>
    </html>
  );
}
